# Generated by Django 3.1.5 on 2021-07-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Item',
        ),
    ]
