# Generated by Django 3.1.5 on 2021-07-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210724_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='facebook',
            new_name='fiyat',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='linkedin',
            new_name='lezzeti',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='twitter',
            new_name='üretim_tarihi',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='youtube',
            new_name='üretim_yeri',
        ),
    ]
