# Generated by Django 3.1.5 on 2021-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210724_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fiyat',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lezzeti',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='üretim_tarihi',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='üretim_yeri',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
