# Generated by Django 3.1.5 on 2021-07-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210726_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='indirimli_fiyat',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/%Y/%m/%d/'),
        ),
    ]
