# Generated by Django 3.1.5 on 2021-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210726_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Tag',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Ürün Etiketi'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Sayfa Etiketi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ürünün Adı'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Ürünün Başığı'),
        ),
    ]
