# Generated by Django 3.1.5 on 2021-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210726_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stok',
            field=models.BooleanField(default=False),
        ),
    ]
