# Generated by Django 3.1.5 on 2021-07-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('geeks_field', models.CharField(max_length=200, verbose_name='ürün')),
            ],
            bases=('items.item',),
        ),
    ]
