# Generated by Django 3.1.5 on 2021-07-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_itemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
