# Generated by Django 3.1.5 on 2021-07-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20210728_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'ürünler'},
        ),
    ]
