# Generated by Django 3.1.5 on 2021-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210728_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='items.Tag'),
        ),
    ]
