# Generated by Django 3.1.5 on 2021-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'kategoriler'},
        ),
        migrations.AlterField(
            model_name='item',
            name='stok',
            field=models.BooleanField(default=False, verbose_name='stokta'),
        ),
    ]
