# Generated by Django 3.1.5 on 2021-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20210801_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='items.Tag', verbose_name='Ürünün Türü'),
        ),
    ]
