# Generated by Django 3.1.5 on 2021-08-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Is',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('Telefon', models.CharField(max_length=100)),
                ('Ücret_Beklentiniz', models.CharField(max_length=100)),
                ('İşe_Başlayabilme_Tarihiniz', models.DateTimeField()),
                ('Askerlik_Durumu', models.CharField(max_length=100)),
                ('Cinsiyet', models.CharField(max_length=100)),
                ('Başvurduğunuz_Pozisyon', models.CharField(max_length=100)),
                ('Referanslarınız', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_Soyad', models.CharField(max_length=100)),
                ('Okul', models.CharField(max_length=100)),
                ('Bölüm', models.CharField(max_length=100)),
                ('Telefon', models.CharField(max_length=100)),
                ('Yaş', models.CharField(max_length=100)),
            ],
        ),
    ]
