# Generated by Django 3.1.5 on 2021-08-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_is_staj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is',
            old_name='message',
            new_name='mesaj',
        ),
        migrations.RemoveField(
            model_name='is',
            name='email',
        ),
    ]
