# Generated by Django 3.1.5 on 2021-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210801_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='is',
            options={'verbose_name': 'iş başvurusu', 'verbose_name_plural': 'iş başvuruları'},
        ),
        migrations.AlterModelOptions(
            name='staj',
            options={'verbose_name': 'staj başvurusu', 'verbose_name_plural': 'staj başvuruları'},
        ),
        migrations.AlterField(
            model_name='is',
            name='Referanslarınız',
            field=models.TextField(),
        ),
    ]
