# Generated by Django 3.1.5 on 2021-08-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210801_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Gelen Mesaj', 'verbose_name_plural': 'Gelen Mesajlar'},
        ),
    ]
