# Generated by Django 3.1.5 on 2021-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210801_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='is',
            name='İşe_Başlayabilme_Tarihiniz',
            field=models.CharField(max_length=100),
        ),
    ]
